sudo: false
language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust:
      - beta
      - nightly
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt
script:
- cargo fmt -- --write-mode=diff
- cargo build
- cargo test
- cargo doc
