[package]
name = "rfc822_sanitizer"
version = "0.3.1"
authors = ["Jordan Petridis <jordanpetridis@protonmail.com>"]
description = "A helper funtion trying to fix invalid rfc822/2822 inputs "
repository = "https://github.com/alatiera/rfc822_sanitizer"
homepage = "https://github.com/alatiera/rfc822_sanitizer"
documentation = "https://docs.rs/rfc822_sanitizer/0.1.0/rfc822_sanitizer/"
readme = "README.md"
license = "GPL-3.0+"

[dependencies]
chrono = "0.4"
regex = "0.2"
lazy_static = "0.2.9"

[badges]
travis-ci = { repository = "alatiera/rfc822_sanitizer", branch = "master"}
appveyor = { repository = "alatiera/rfc822_sanitizer", branch = "master", service = "github" }
