unstable_features = true
verbose = false
max_width = 100
comment_width = 100
wrap_comments = true
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"
reorder_imports = false
write_mode = "Overwrite"
condense_wildcard_suffixes = false
format_strings = true
normalize_comments = true