verbose = false
disable_all_formatting = false
skip_children = false
max_width = 100
error_on_line_overflow = true
error_on_line_overflow_comments = true
wrap_comments = true
tab_spaces = 4
fn_call_width = 60
newline_style = "Unix"
fn_call_style = "Block"
report_todo = "Never"
report_fixme = "Never"
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imports = false
hard_tabs = false
spaces_within_parens = false
use_try_shorthand = false
write_mode = "Overwrite"
merge_derives = true
array_horizontal_layout_threshold = 5
condense_wildcard_suffixes = true
# rustfmt 0.2.7 panics with format_string = true atm
# format_strings = true
chain_one_line_max = 60
chain_split_single_child = false
