verbose = false
disable_all_formatting = false
skip_children = false
max_width = 100
comment_width = 100
wrap_comments = true
error_on_line_overflow = true
error_on_line_overflow_comments = true
tab_spaces = 4
fn_call_width = 60
newline_style = "Unix"
fn_call_style = "Block"
report_todo = "Never"
report_fixme = "Never"
reorder_extern_crates = true
reorder_extern_crates_in_group = true
reorder_imports = false
hard_tabs = false
spaces_within_parens = false
write_mode = "Overwrite"
merge_derives = true
condense_wildcard_suffixes = true
format_strings = true
multiline_closure_forces_block = true
attributes_on_same_line_as_field = true
attributes_on_same_line_as_variant = true